<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Propuesta Avance 2 &amp; 3 | Precio Del Oro</title>
  <meta name="description" content="Capítulo 2 Propuesta Avance 2 &amp; 3 | Precio Del Oro" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Propuesta Avance 2 &amp; 3 | Precio Del Oro" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Propuesta Avance 2 &amp; 3 | Precio Del Oro" />
  
  
  

<meta name="author" content="Grupo 2: Santiago Reyes, Francisco Santos, Fabian Maldonado" />


<meta name="date" content="2024-06-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="avance-4.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Precio del Oro</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> DATA SET SELECCIONADO</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#nombre-daily-gold-price-2014-2022-time-series-en-kaggle"><i class="fa fa-check"></i><b>1.1</b> NOMBRE: Daily Gold Price (2014-2022) Time Series en Kaggle</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#descripción"><i class="fa fa-check"></i><b>1.2</b> DESCRIPCIÓN:</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#rango-de-fechas01012014-05082022"><i class="fa fa-check"></i><b>1.3</b> RANGO DE FECHAS:01/01/2014-05/08/2022</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#registros-2.227"><i class="fa fa-check"></i><b>1.4</b> REGISTROS: 2.227</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#variables"><i class="fa fa-check"></i><b>1.5</b> VARIABLES:</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#importancia"><i class="fa fa-check"></i><b>1.6</b> IMPORTANCIA:</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#relevancia-económica"><i class="fa fa-check"></i><b>1.6.1</b> <strong>Relevancia económica</strong>:</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#análisis-de-tendencias"><i class="fa fa-check"></i><b>1.6.2</b> <strong>Análisis de tendencias</strong>:</a></li>
<li class="chapter" data-level="1.6.3" data-path="index.html"><a href="index.html#modelos-de-predicción"><i class="fa fa-check"></i><b>1.6.3</b> <strong>Modelos de predicción</strong>:</a></li>
<li class="chapter" data-level="1.6.4" data-path="index.html"><a href="index.html#investigación-académica"><i class="fa fa-check"></i><b>1.6.4</b> <strong>Investigación académica</strong>:</a></li>
<li class="chapter" data-level="1.6.5" data-path="index.html"><a href="index.html#granularidad-diaria"><i class="fa fa-check"></i><b>1.6.5</b> <strong>Granularidad diaria</strong>:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html"><i class="fa fa-check"></i><b>2</b> Propuesta Avance 2 &amp; 3</a>
<ul>
<li class="chapter" data-level="2.1" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#cargar-librerias-a-usar"><i class="fa fa-check"></i><b>2.1</b> Cargar Librerias a usar</a></li>
<li class="chapter" data-level="2.2" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#cargar-la-data-del-data-set"><i class="fa fa-check"></i><b>2.2</b> Cargar la data del Data set</a></li>
<li class="chapter" data-level="2.3" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#limpieza-de-datos"><i class="fa fa-check"></i><b>2.3</b> Limpieza de Datos</a></li>
<li class="chapter" data-level="2.4" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#padding-imputation"><i class="fa fa-check"></i><b>2.4</b> Padding &amp; imputation</a></li>
<li class="chapter" data-level="2.5" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#exploración-de-la-data"><i class="fa fa-check"></i><b>2.5</b> Exploración de la data</a></li>
<li class="chapter" data-level="2.6" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#descomposición-de-la-serie-temporal"><i class="fa fa-check"></i><b>2.6</b> Descomposición de la Serie Temporal</a></li>
<li class="chapter" data-level="2.7" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#análisis-de-estacionalidad"><i class="fa fa-check"></i><b>2.7</b> Análisis de estacionalidad</a></li>
<li class="chapter" data-level="2.8" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#análisis-de-diferenciación"><i class="fa fa-check"></i><b>2.8</b> Análisis de Diferenciación</a></li>
<li class="chapter" data-level="2.9" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#transformación-para-controlar-la-tendencia-y-variabilidad"><i class="fa fa-check"></i><b>2.9</b> Transformación para Controlar la Tendencia y Variabilidad</a></li>
<li class="chapter" data-level="2.10" data-path="propuesta-avance-2-3.html"><a href="propuesta-avance-2-3.html#justificación"><i class="fa fa-check"></i><b>2.10</b> Justificación</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="avance-4.html"><a href="avance-4.html"><i class="fa fa-check"></i><b>3</b> Avance 4</a>
<ul>
<li class="chapter" data-level="3.1" data-path="avance-4.html"><a href="avance-4.html#método-de-holt-winters"><i class="fa fa-check"></i><b>3.1</b> Método de Holt-Winters:</a></li>
<li class="chapter" data-level="3.2" data-path="avance-4.html"><a href="avance-4.html#suavizamiento-exponencial"><i class="fa fa-check"></i><b>3.2</b> Suavizamiento Exponencial:</a></li>
<li class="chapter" data-level="3.3" data-path="avance-4.html"><a href="avance-4.html#pronóstico"><i class="fa fa-check"></i><b>3.3</b> Pronóstico:</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="avance-4.html"><a href="avance-4.html#suavizamiento-exponencial-1"><i class="fa fa-check"></i><b>3.3.1</b> Suavizamiento Exponencial:</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="avance-4.html"><a href="avance-4.html#visualización"><i class="fa fa-check"></i><b>3.4</b> Visualización:</a></li>
<li class="chapter" data-level="3.5" data-path="avance-4.html"><a href="avance-4.html#calculando-las-métricas-para-el-suavizamiento-exponencial"><i class="fa fa-check"></i><b>3.5</b> Calculando las métricas para el suavizamiento exponencial</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="avance-5.html"><a href="avance-5.html"><i class="fa fa-check"></i><b>4</b> Avance 5</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Precio Del Oro</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="propuesta-avance-2-3" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo 2</span> Propuesta Avance 2 &amp; 3<a href="propuesta-avance-2-3.html#propuesta-avance-2-3" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="cargar-librerias-a-usar" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Cargar Librerias a usar<a href="propuesta-avance-2-3.html#cargar-librerias-a-usar" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="propuesta-avance-2-3.html#cb1-1" tabindex="-1"></a><span class="fu">suppressMessages</span>({</span>
<span id="cb1-2"><a href="propuesta-avance-2-3.html#cb1-2" tabindex="-1"></a></span>
<span id="cb1-3"><a href="propuesta-avance-2-3.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(lubridate) </span>
<span id="cb1-4"><a href="propuesta-avance-2-3.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(forecast) </span>
<span id="cb1-5"><a href="propuesta-avance-2-3.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(MLmetrics) </span>
<span id="cb1-6"><a href="propuesta-avance-2-3.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(tseries) </span>
<span id="cb1-7"><a href="propuesta-avance-2-3.html#cb1-7" tabindex="-1"></a><span class="fu">library</span>(TSstudio) </span>
<span id="cb1-8"><a href="propuesta-avance-2-3.html#cb1-8" tabindex="-1"></a><span class="fu">library</span>(padr) </span>
<span id="cb1-9"><a href="propuesta-avance-2-3.html#cb1-9" tabindex="-1"></a><span class="fu">library</span>(imputeTS)</span>
<span id="cb1-10"><a href="propuesta-avance-2-3.html#cb1-10" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-11"><a href="propuesta-avance-2-3.html#cb1-11" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-12"><a href="propuesta-avance-2-3.html#cb1-12" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span>
<span id="cb1-13"><a href="propuesta-avance-2-3.html#cb1-13" tabindex="-1"></a></span>
<span id="cb1-14"><a href="propuesta-avance-2-3.html#cb1-14" tabindex="-1"></a>})</span></code></pre></div>
</div>
<div id="cargar-la-data-del-data-set" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Cargar la data del Data set<a href="propuesta-avance-2-3.html#cargar-la-data-del-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="propuesta-avance-2-3.html#cb2-1" tabindex="-1"></a>data <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;Gold Price.csv&quot;</span>)</span>
<span id="cb2-2"><a href="propuesta-avance-2-3.html#cb2-2" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<pre><code>##         Date Price  Open  High   Low Volume  Chg.
## 1 2014-01-01 29542 29435 29598 29340   2930  0.25
## 2 2014-01-02 29975 29678 30050 29678   3140  1.47
## 3 2014-01-03 29727 30031 30125 29539   3050 -0.83
## 4 2014-01-04 29279 29279 29279 29279      0 -1.51
## 5 2014-01-06 29119 29300 29395 29051  24380 -0.55
## 6 2014-01-07 28959 29130 29195 28912  18710 -0.55</code></pre>
</div>
<div id="limpieza-de-datos" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Limpieza de Datos<a href="propuesta-avance-2-3.html#limpieza-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="propuesta-avance-2-3.html#cb4-1" tabindex="-1"></a><span class="co"># Validar los tipos de datos de cada Columna</span></span>
<span id="cb4-2"><a href="propuesta-avance-2-3.html#cb4-2" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2227 obs. of  7 variables:
##  $ Date  : chr  &quot;2014-01-01&quot; &quot;2014-01-02&quot; &quot;2014-01-03&quot; &quot;2014-01-04&quot; ...
##  $ Price : int  29542 29975 29727 29279 29119 28959 28934 28997 29169 29312 ...
##  $ Open  : int  29435 29678 30031 29279 29300 29130 28916 28990 29030 29170 ...
##  $ High  : int  29598 30050 30125 29279 29395 29195 29029 29053 29198 29330 ...
##  $ Low   : int  29340 29678 29539 29279 29051 28912 28820 28865 28960 29133 ...
##  $ Volume: int  2930 3140 3050 0 24380 18710 18140 15130 15810 13780 ...
##  $ Chg.  : num  0.25 1.47 -0.83 -1.51 -0.55 -0.55 -0.09 0.22 0.59 0.49 ...</code></pre>
<p>Se ajusta la columna “Date” está en tipo “character”, por lo tanto toca convertir esta en formato de Tiempo</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="propuesta-avance-2-3.html#cb6-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="propuesta-avance-2-3.html#cb6-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">ymd</span>(Date))</span>
<span id="cb6-3"><a href="propuesta-avance-2-3.html#cb6-3" tabindex="-1"></a></span>
<span id="cb6-4"><a href="propuesta-avance-2-3.html#cb6-4" tabindex="-1"></a><span class="fu">str</span>(data)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2227 obs. of  7 variables:
##  $ Date  : Date, format: &quot;2014-01-01&quot; &quot;2014-01-02&quot; ...
##  $ Price : int  29542 29975 29727 29279 29119 28959 28934 28997 29169 29312 ...
##  $ Open  : int  29435 29678 30031 29279 29300 29130 28916 28990 29030 29170 ...
##  $ High  : int  29598 30050 30125 29279 29395 29195 29029 29053 29198 29330 ...
##  $ Low   : int  29340 29678 29539 29279 29051 28912 28820 28865 28960 29133 ...
##  $ Volume: int  2930 3140 3050 0 24380 18710 18140 15130 15810 13780 ...
##  $ Chg.  : num  0.25 1.47 -0.83 -1.51 -0.55 -0.55 -0.09 0.22 0.59 0.49 ...</code></pre>
<p>Se identifica que Todas las columnas se encuentran en el tipo correcto.</p>
</div>
<div id="padding-imputation" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Padding &amp; imputation<a href="propuesta-avance-2-3.html#padding-imputation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Si observamos la data solo comprende fechas entre semana, pero en series de tiempo deberíamos tener la data mas completa en la medida de lo posible.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="propuesta-avance-2-3.html#cb8-1" tabindex="-1"></a><span class="co"># Padding</span></span>
<span id="cb8-2"><a href="propuesta-avance-2-3.html#cb8-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="propuesta-avance-2-3.html#cb8-3" tabindex="-1"></a>  <span class="fu">pad</span>(<span class="at">interval =</span> <span class="st">&quot;day&quot;</span>) </span>
<span id="cb8-4"><a href="propuesta-avance-2-3.html#cb8-4" tabindex="-1"></a></span>
<span id="cb8-5"><a href="propuesta-avance-2-3.html#cb8-5" tabindex="-1"></a></span>
<span id="cb8-6"><a href="propuesta-avance-2-3.html#cb8-6" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb8-7"><a href="propuesta-avance-2-3.html#cb8-7" tabindex="-1"></a>  <span class="co"># Imputar NA values con la última observación</span></span>
<span id="cb8-8"><a href="propuesta-avance-2-3.html#cb8-8" tabindex="-1"></a>  data_clean <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">na.locf</span>()</span>
<span id="cb8-9"><a href="propuesta-avance-2-3.html#cb8-9" tabindex="-1"></a>})</span>
<span id="cb8-10"><a href="propuesta-avance-2-3.html#cb8-10" tabindex="-1"></a></span>
<span id="cb8-11"><a href="propuesta-avance-2-3.html#cb8-11" tabindex="-1"></a><span class="fu">head</span>(data_clean)</span></code></pre></div>
<pre><code>##         Date Price  Open  High   Low Volume  Chg.
## 1 2014-01-01 29542 29435 29598 29340   2930  0.25
## 2 2014-01-02 29975 29678 30050 29678   3140  1.47
## 3 2014-01-03 29727 30031 30125 29539   3050 -0.83
## 4 2014-01-04 29279 29279 29279 29279      0 -1.51
## 5 2014-01-05 29279 29279 29279 29279      0 -1.51
## 6 2014-01-06 29119 29300 29395 29051  24380 -0.55</code></pre>
</div>
<div id="exploración-de-la-data" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Exploración de la data<a href="propuesta-avance-2-3.html#exploración-de-la-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para explorar la data debemos primero crear el objeto de serie de tiempo</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="propuesta-avance-2-3.html#cb10-1" tabindex="-1"></a><span class="co"># ts</span></span>
<span id="cb10-2"><a href="propuesta-avance-2-3.html#cb10-2" tabindex="-1"></a>data_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="at">data =</span> data_clean<span class="sc">$</span>Price, <span class="at">start =</span> <span class="dv">2014</span>, <span class="at">frequency =</span> <span class="dv">7</span><span class="sc">*</span><span class="dv">4</span><span class="sc">*</span><span class="dv">12</span>)</span>
<span id="cb10-3"><a href="propuesta-avance-2-3.html#cb10-3" tabindex="-1"></a>data_ts <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="propuesta-avance-2-3.html#cb10-4" tabindex="-1"></a><span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-6-1.png" width="672" />
Se observa un comportamiento INCREMENTAL a traves del tiempo y adicionalmente se podria inferir un modelo multiplicativo</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="propuesta-avance-2-3.html#cb11-1" tabindex="-1"></a>  <span class="co"># Calcular el promedio móvil</span></span>
<span id="cb11-2"><a href="propuesta-avance-2-3.html#cb11-2" tabindex="-1"></a>  promedio_movil <span class="ot">&lt;-</span> <span class="fu">ma</span>(data_ts, <span class="at">order =</span> <span class="dv">12</span>)  </span>
<span id="cb11-3"><a href="propuesta-avance-2-3.html#cb11-3" tabindex="-1"></a>  <span class="fu">autoplot</span>(data_ts) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Serie de Tiempo&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="propuesta-avance-2-3.html#cb11-4" tabindex="-1"></a>    <span class="fu">autolayer</span>(promedio_movil, <span class="at">series =</span> <span class="st">&quot;Promedio Móvil&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 12 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Se observa que el promedio móvil sigue de cerca la serie temporal, lo que sugiere una presencia limitada de ruido en los datos y una tendencia clara en su evolución.</p>
</div>
<div id="descomposición-de-la-serie-temporal" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Descomposición de la Serie Temporal<a href="propuesta-avance-2-3.html#descomposición-de-la-serie-temporal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se realiza la descomposición de la serie temporal en sus componentes de tendencia, estacionalidad y residuos</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="propuesta-avance-2-3.html#cb13-1" tabindex="-1"></a>data_decompose <span class="ot">&lt;-</span> data_ts <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="propuesta-avance-2-3.html#cb13-2" tabindex="-1"></a>  <span class="fu">decompose</span>(<span class="at">type =</span> <span class="st">&quot;multiplicative&quot;</span>)</span>
<span id="cb13-3"><a href="propuesta-avance-2-3.html#cb13-3" tabindex="-1"></a>  </span>
<span id="cb13-4"><a href="propuesta-avance-2-3.html#cb13-4" tabindex="-1"></a>data_decompose <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="propuesta-avance-2-3.html#cb13-5" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Se evidencia claramente una tendencia lineal en los datos, acompañada de un patrón de estacionalidad adicional.</p>
</div>
<div id="análisis-de-estacionalidad" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Análisis de estacionalidad<a href="propuesta-avance-2-3.html#análisis-de-estacionalidad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="propuesta-avance-2-3.html#cb14-1" tabindex="-1"></a>data_decompose<span class="sc">$</span>seasonal <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="propuesta-avance-2-3.html#cb14-2" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Después de la visualización del componente estacional de la serie temporal, se procederá a analizar y validar un posible patrón en los precios del oro entre los años 2014 y 2023. Este análisis ayudará a comprender mejor la naturaleza de la estacionalidad presente en los datos a lo largo de este período</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="propuesta-avance-2-3.html#cb15-1" tabindex="-1"></a><span class="fu">ggseasonplot</span>(data_ts, <span class="at">year.labels =</span> <span class="cn">TRUE</span>, <span class="at">year.labels.left =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb15-2"><a href="propuesta-avance-2-3.html#cb15-2" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gráfico Estacional de Precios del Oro (Múltiples Años)&quot;</span>, </span>
<span id="cb15-3"><a href="propuesta-avance-2-3.html#cb15-3" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Mes&quot;</span>, </span>
<span id="cb15-4"><a href="propuesta-avance-2-3.html#cb15-4" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Precio&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="propuesta-avance-2-3.html#cb15-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Se observa un patrón recurrente en los precios, con picos y valles que parecen repetirse cada año. Se identifica una trendencia incremental constante del periodo 2019 al 2022 principalmente</p>
<p>Alicamos La prueba de Dickey-Fuller Aumentada (ADF) para determinar si una serie temporal es estacionaria o no.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="propuesta-avance-2-3.html#cb16-1" tabindex="-1"></a><span class="fu">suppressMessages</span>({</span>
<span id="cb16-2"><a href="propuesta-avance-2-3.html#cb16-2" tabindex="-1"></a></span>
<span id="cb16-3"><a href="propuesta-avance-2-3.html#cb16-3" tabindex="-1"></a><span class="co"># Prueba de estacionariedad (ADF)</span></span>
<span id="cb16-4"><a href="propuesta-avance-2-3.html#cb16-4" tabindex="-1"></a>adf_test <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(data_ts)</span>
<span id="cb16-5"><a href="propuesta-avance-2-3.html#cb16-5" tabindex="-1"></a>adf_test</span>
<span id="cb16-6"><a href="propuesta-avance-2-3.html#cb16-6" tabindex="-1"></a></span>
<span id="cb16-7"><a href="propuesta-avance-2-3.html#cb16-7" tabindex="-1"></a></span>
<span id="cb16-8"><a href="propuesta-avance-2-3.html#cb16-8" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  data_ts
## Dickey-Fuller = -2.1155, Lag order = 14, p-value = 0.5294
## alternative hypothesis: stationary</code></pre>
<p>La prueba de Dickey-Fuller aumentada (ADF) identifica que la serie temporal no es estacionaria. Esto se basa en el estadístico de prueba (-2.1155) y el valor p (0.5294). Dado que el valor p es mayor que el nivel de significancia típico de 0.05, no hay suficiente evidencia para rechazar la hipótesis nula de no estacionariedad.</p>
<p>Dado que la serie no es estacionaria según la prueba ADF, Proceedemos con la diferenciación</p>
</div>
<div id="análisis-de-diferenciación" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Análisis de Diferenciación<a href="propuesta-avance-2-3.html#análisis-de-diferenciación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se realiza un analisis comparativo de los meses identificando el comportamiento</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="propuesta-avance-2-3.html#cb18-1" tabindex="-1"></a>data_clean <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="propuesta-avance-2-3.html#cb18-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month =</span> <span class="fu">month</span>(Date, <span class="at">label =</span> T)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="propuesta-avance-2-3.html#cb18-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">seasons =</span> data_decompose<span class="sc">$</span>seasonal) <span class="sc">%&gt;%</span> </span>
<span id="cb18-4"><a href="propuesta-avance-2-3.html#cb18-4" tabindex="-1"></a>  <span class="fu">group_by</span>(Month) <span class="sc">%&gt;%</span> </span>
<span id="cb18-5"><a href="propuesta-avance-2-3.html#cb18-5" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(seasons)) <span class="sc">%&gt;%</span>   </span>
<span id="cb18-6"><a href="propuesta-avance-2-3.html#cb18-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Month, total)) <span class="sc">+</span></span>
<span id="cb18-7"><a href="propuesta-avance-2-3.html#cb18-7" tabindex="-1"></a>  <span class="fu">geom_col</span>()<span class="sc">+</span></span>
<span id="cb18-8"><a href="propuesta-avance-2-3.html#cb18-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-12-1.png" width="672" />
El análisis de la estacionalidad mensual revela patrones en los precios del oro a lo largo del año. Se observa que estos son más altos durante enero a julio, mientras que disminuyen de agosto a diciembre</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="propuesta-avance-2-3.html#cb19-1" tabindex="-1"></a><span class="co"># Diferenciación de la serie temporal</span></span>
<span id="cb19-2"><a href="propuesta-avance-2-3.html#cb19-2" tabindex="-1"></a>diff_data_ts <span class="ot">&lt;-</span> <span class="fu">diff</span>(data_ts)</span>
<span id="cb19-3"><a href="propuesta-avance-2-3.html#cb19-3" tabindex="-1"></a></span>
<span id="cb19-4"><a href="propuesta-avance-2-3.html#cb19-4" tabindex="-1"></a><span class="fu">autoplot</span>(diff_data_ts) <span class="sc">+</span> </span>
<span id="cb19-5"><a href="propuesta-avance-2-3.html#cb19-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie Diferenciada&quot;</span>, </span>
<span id="cb19-6"><a href="propuesta-avance-2-3.html#cb19-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Diferencia&quot;</span>, </span>
<span id="cb19-7"><a href="propuesta-avance-2-3.html#cb19-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Con este grafico observamos parecen más amplias entre sí durante el año 2020 y 2021, lo que indica cambios significativos en el comportamiento de la serie durante ese año</p>
<p>Continuamos el análisis al representar tanto la serie temporal original como la serie diferenciada en un único gráfico.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="propuesta-avance-2-3.html#cb20-1" tabindex="-1"></a><span class="co"># Diferenciación de la serie temporal</span></span>
<span id="cb20-2"><a href="propuesta-avance-2-3.html#cb20-2" tabindex="-1"></a>diff_data_ts <span class="ot">&lt;-</span> <span class="fu">diff</span>(data_ts)</span>
<span id="cb20-3"><a href="propuesta-avance-2-3.html#cb20-3" tabindex="-1"></a></span>
<span id="cb20-4"><a href="propuesta-avance-2-3.html#cb20-4" tabindex="-1"></a></span>
<span id="cb20-5"><a href="propuesta-avance-2-3.html#cb20-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb20-6"><a href="propuesta-avance-2-3.html#cb20-6" tabindex="-1"></a><span class="fu">plot</span>(data_ts, <span class="at">main=</span><span class="st">&quot;Serie Original&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Valor&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Tiempo&quot;</span>)</span>
<span id="cb20-7"><a href="propuesta-avance-2-3.html#cb20-7" tabindex="-1"></a><span class="fu">plot</span>(diff_data_ts, <span class="at">main=</span><span class="st">&quot;Serie Diferenciada&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Diferencia&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Tiempo&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-14-1.png" width="672" />
Esto nos permite comparar visualmente cómo cambian los datos después de aplicar la diferenciación.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="propuesta-avance-2-3.html#cb21-1" tabindex="-1"></a><span class="co"># Calcular la función de autocorrelación (ACF)</span></span>
<span id="cb21-2"><a href="propuesta-avance-2-3.html#cb21-2" tabindex="-1"></a>acf_diff <span class="ot">&lt;-</span> <span class="fu">acf</span>(diff_data_ts, <span class="at">main =</span> <span class="st">&quot;Función de Autocorrelación (ACF) de la Serie Diferenciada&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="propuesta-avance-2-3.html#cb22-1" tabindex="-1"></a><span class="co"># Calcular la función de autocorrelación parcial (PACF)</span></span>
<span id="cb22-2"><a href="propuesta-avance-2-3.html#cb22-2" tabindex="-1"></a>pacf_diff <span class="ot">&lt;-</span> <span class="fu">pacf</span>(diff_data_ts, <span class="at">main =</span> <span class="st">&quot;Función de Autocorrelación Parcial (PACF) de la Serie Diferenciada&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<p>Los coeficientes de correlación fuera de estos límites son estadísticamente significativos. el limigte superio es de :0.0349826 y el inferior de: -0.0349826</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="propuesta-avance-2-3.html#cb23-1" tabindex="-1"></a><span class="fu">suppressMessages</span>({</span>
<span id="cb23-2"><a href="propuesta-avance-2-3.html#cb23-2" tabindex="-1"></a></span>
<span id="cb23-3"><a href="propuesta-avance-2-3.html#cb23-3" tabindex="-1"></a><span class="co"># Prueba ADF en la serie diferenciada</span></span>
<span id="cb23-4"><a href="propuesta-avance-2-3.html#cb23-4" tabindex="-1"></a>adf_test_diff <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(diff_data_ts)</span>
<span id="cb23-5"><a href="propuesta-avance-2-3.html#cb23-5" tabindex="-1"></a>adf_test_diff</span>
<span id="cb23-6"><a href="propuesta-avance-2-3.html#cb23-6" tabindex="-1"></a></span>
<span id="cb23-7"><a href="propuesta-avance-2-3.html#cb23-7" tabindex="-1"></a>})</span></code></pre></div>
<pre><code>## Warning in adf.test(diff_data_ts): p-value smaller than printed p-value</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  diff_data_ts
## Dickey-Fuller = -15.347, Lag order = 14, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<p>Se aplico la prueba ADF en la serie diferenciada arrojó un estadístico de prueba de -15.347 y un valor p de 0.01. Estos resultados indican una evidencia que la serie temporal tiene una tendencia constante unitaria , lo que implica que la serie es estacionaria.</p>
</div>
<div id="transformación-para-controlar-la-tendencia-y-variabilidad" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Transformación para Controlar la Tendencia y Variabilidad<a href="propuesta-avance-2-3.html#transformación-para-controlar-la-tendencia-y-variabilidad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="propuesta-avance-2-3.html#cb26-1" tabindex="-1"></a><span class="co"># Transformación logarítmica</span></span>
<span id="cb26-2"><a href="propuesta-avance-2-3.html#cb26-2" tabindex="-1"></a>log_data_ts <span class="ot">&lt;-</span> <span class="fu">log</span>(data_ts)</span>
<span id="cb26-3"><a href="propuesta-avance-2-3.html#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="propuesta-avance-2-3.html#cb26-4" tabindex="-1"></a><span class="co"># Gráfico de la serie transformada</span></span>
<span id="cb26-5"><a href="propuesta-avance-2-3.html#cb26-5" tabindex="-1"></a><span class="fu">plot</span>(log_data_ts, <span class="at">main=</span><span class="st">&quot;Serie Transformada (Logarítmica)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Valor Transformado&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;Tiempo&quot;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="propuesta-avance-2-3.html#cb27-1" tabindex="-1"></a><span class="co"># Cargar el paquete knitr</span></span>
<span id="cb27-2"><a href="propuesta-avance-2-3.html#cb27-2" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div>
<pre><code>## Warning: package &#39;knitr&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="propuesta-avance-2-3.html#cb29-1" tabindex="-1"></a><span class="co"># métricas antes de la transformación</span></span>
<span id="cb29-2"><a href="propuesta-avance-2-3.html#cb29-2" tabindex="-1"></a>cv_before <span class="ot">&lt;-</span> <span class="fu">sd</span>(data_ts) <span class="sc">/</span> <span class="fu">mean</span>(data_ts) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb29-3"><a href="propuesta-avance-2-3.html#cb29-3" tabindex="-1"></a>sd_before <span class="ot">&lt;-</span> <span class="fu">sd</span>(data_ts)</span>
<span id="cb29-4"><a href="propuesta-avance-2-3.html#cb29-4" tabindex="-1"></a>iqr_before <span class="ot">&lt;-</span> <span class="fu">IQR</span>(data_ts)</span>
<span id="cb29-5"><a href="propuesta-avance-2-3.html#cb29-5" tabindex="-1"></a></span>
<span id="cb29-6"><a href="propuesta-avance-2-3.html#cb29-6" tabindex="-1"></a><span class="co"># Aplicar la transformación logarítmica</span></span>
<span id="cb29-7"><a href="propuesta-avance-2-3.html#cb29-7" tabindex="-1"></a>log_data_ts <span class="ot">&lt;-</span> <span class="fu">log</span>(data_ts)</span>
<span id="cb29-8"><a href="propuesta-avance-2-3.html#cb29-8" tabindex="-1"></a></span>
<span id="cb29-9"><a href="propuesta-avance-2-3.html#cb29-9" tabindex="-1"></a><span class="co"># métricas después de la transformación</span></span>
<span id="cb29-10"><a href="propuesta-avance-2-3.html#cb29-10" tabindex="-1"></a>cv_after <span class="ot">&lt;-</span> <span class="fu">sd</span>(log_data_ts) <span class="sc">/</span> <span class="fu">mean</span>(log_data_ts) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb29-11"><a href="propuesta-avance-2-3.html#cb29-11" tabindex="-1"></a>sd_after <span class="ot">&lt;-</span> <span class="fu">sd</span>(log_data_ts)</span>
<span id="cb29-12"><a href="propuesta-avance-2-3.html#cb29-12" tabindex="-1"></a>iqr_after <span class="ot">&lt;-</span> <span class="fu">IQR</span>(log_data_ts)</span>
<span id="cb29-13"><a href="propuesta-avance-2-3.html#cb29-13" tabindex="-1"></a></span>
<span id="cb29-14"><a href="propuesta-avance-2-3.html#cb29-14" tabindex="-1"></a><span class="co"># Crear con los resultados</span></span>
<span id="cb29-15"><a href="propuesta-avance-2-3.html#cb29-15" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-16"><a href="propuesta-avance-2-3.html#cb29-16" tabindex="-1"></a>  Métrica <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Coeficiente de Variación (CV)&quot;</span>, <span class="st">&quot;Desviación Estándar&quot;</span>, <span class="st">&quot;Rango Intercuartílico (IQR)&quot;</span>),</span>
<span id="cb29-17"><a href="propuesta-avance-2-3.html#cb29-17" tabindex="-1"></a>  Antes_de_la_Transformación <span class="ot">=</span> <span class="fu">c</span>(cv_before, sd_before, iqr_before),</span>
<span id="cb29-18"><a href="propuesta-avance-2-3.html#cb29-18" tabindex="-1"></a>  Después_de_la_Transformación <span class="ot">=</span> <span class="fu">c</span>(cv_after, sd_after, iqr_after)</span>
<span id="cb29-19"><a href="propuesta-avance-2-3.html#cb29-19" tabindex="-1"></a>)</span>
<span id="cb29-20"><a href="propuesta-avance-2-3.html#cb29-20" tabindex="-1"></a></span>
<span id="cb29-21"><a href="propuesta-avance-2-3.html#cb29-21" tabindex="-1"></a><span class="co"># Imprimir </span></span>
<span id="cb29-22"><a href="propuesta-avance-2-3.html#cb29-22" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(results, <span class="at">caption =</span> <span class="st">&quot;Métricas antes y después de la transformación&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-18">Table 2.1: </span>Métricas antes y después de la transformación</caption>
<colgroup>
<col width="34%" />
<col width="31%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Métrica</th>
<th align="right">Antes_de_la_Transformación</th>
<th align="right">Después_de_la_Transformación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Coeficiente de Variación (CV)</td>
<td align="right">25.42391</td>
<td align="right">2.2939376</td>
</tr>
<tr class="even">
<td align="left">Desviación Estándar</td>
<td align="right">8961.58310</td>
<td align="right">0.2394944</td>
</tr>
<tr class="odd">
<td align="left">Rango Intercuartílico (IQR)</td>
<td align="right">17332.00000</td>
<td align="right">0.4742370</td>
</tr>
</tbody>
</table>
<p>Antes de la transformación, el coeficiente de variación (CV) es 25.42, la desviación estándar es 8961.58 y el rango intercuartílico (IQR) es 17332.
Después de la transformación, el CV se reduce significativamente a 2.29, la desviación estándar se reduce a 0.24 y el IQR se reduce a 0.47. Estas reducciones indican una disminución significativa en la variabilidad de la serie después de la transformación.</p>
</div>
<div id="justificación" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> Justificación<a href="propuesta-avance-2-3.html#justificación" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Prueba de Dickey-Fuller (ADF) estacionariedad :</li>
</ol>
<p>Es importante evaluar la estacionariedad de la serie temporal antes de aplicar modelos de series temporales. La prueba ADF nos permite determinar si la serie es estacionaria o no, lo que influye en la selección y aplicación de modelos adecuados.</p>
<ol start="2" style="list-style-type: decimal">
<li>Diferenciación de la Serie Temporal:</li>
</ol>
<p>La diferenciación es un paso común para lograr la estacionariedad en series temporales no estacionarias. Eliminar tendencias y patrones no estacionarios permite aplicar modelos más simples y eficientes, adicionalmente mejorar la interpretabilidad de los resultados al eliminar tendencias y variaciones.</p>
<ol start="3" style="list-style-type: decimal">
<li>la transformación:</li>
</ol>
<p>La transformación se utilizo para estabilizar la varianza y controlar la tendencia en la serie temporal. Esto es importante para mejorar la interpretacion de los datos y facilitar la identificación de patrones temporales. Además, la reducción de la variabilidad puede hacer que la serie sea más predecible y fácil de modela..</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="avance-4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/SantiagoReyes1994/PrecioDelOro/edit/main/Capitulo-2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/SantiagoReyes1994/PrecioDelOro/blob/main/Capitulo-2.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
